### ISSUE TITLE
Add pulling the boros from the SQL Server database

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-advanced-analysis-gis#15]
After the shapefile, we can do this to show this task with SQL

**Comment by ebrelsford** [comment]
Added the dialogs for doing this and getting the data from SQL Server, but they aren't populated with the proper server name and databases. We'll want to add these once we have access to the database.

**Comment by ebrelsford** [comment]
I'm not sure boroughs are going to be available in the SQL Server db.
