### ISSUE TITLE
QGIS "Getting Started" Data Source Manager

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-advanced-analysis-gis#24]
@ebrelsford Do we want them to use the Data Source Manager (as per `qgis-data-source-manager.png`) rather than Add Layer -> Add Vector Layer?

If so, then we should walk them through the Data Source Manager in more detail.

**Comment by ebrelsford** [comment]
@datapolitan Yes, I can update the slides to make this more clear. You end up in the Data Source Manager no matter how you add data now so it's worth mentioning.
