### ISSUE TITLE
Broken links in GIS slides

### ISSUE THREAD

**Issue by dennisrim** [Datapolitan-Training/parks-advanced-analysis-gis#40]
Here are some links that do not currently work:

- Slide 37 – link to download file leads to 404 (though I see the borough boundaries zip file in the data folder)
- Slide 56 – link leads to https://www.nationalgeographic.org/education/. It should be linking to the NatGeo encyclopedia entry on GIS.
- Slide 64 - link leads to "domain is being updated" page
- Slide 214 – link leads to 404
- Slide 340 – link to Google form survey points to form for **DOT class**

**Comment by datapolitan** [comment]
Links to issues detailing fix for each point raised.

+ [Slide 37](https://github.com/Datapolitan-Training/parks-advanced-analysis-gis/issues/54) – link to download file leads to 404 (though I see the borough boundaries zip file in the data folder)
+ [Slide 56](https://github.com/Datapolitan-Training/parks-advanced-analysis-gis/issues/55) – link leads to https://www.nationalgeographic.org/education/. It should be linking to the NatGeo encyclopedia entry on GIS.
+ [Slide 64](https://github.com/Datapolitan-Training/parks-advanced-analysis-gis/issues/56) - link leads to "domain is being updated" page
+ [Slide 214](https://github.com/Datapolitan-Training/parks-advanced-analysis-gis/issues/58) – link leads to 404
+ [Slide 340](https://github.com/Datapolitan-Training/parks-advanced-analysis-gis/issues/59) – link to Google form survey points to form for DOT class
