### ISSUE TITLE
QuickMapServices Basemaps

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-advanced-analysis-gis#43]
@dennisrim has tried to install the contributor pack, but it may not be the admin privileges. If we can't get them some of the options include: 
+ [Using the QMS toolbox to add our own map service](https://geometalab.tumblr.com/post/173288619092/qgis-tips-tricks-qgis-3-plugin-quickmapservices)
+ Using [the XYZ Tile Server option](https://gis.stackexchange.com/questions/20191/adding-basemaps-from-google-or-bing-in-qgis/217670#217670) to directly load basemaps

**Comment by datapolitan** [comment]
Documentation of the problem:
+ [Blog](http://nextgis.com/blog/quickmapservices/) (in comments)
+ [Github Issue](https://github.com/nextgis/quickmapservices/issues/180)

**Comment by ebrelsford** [comment]
I'm going to update the slides with QMS Search and the DoITT basemap referenced in #50.
