### ISSUE TITLE
Add endpoints for base map service

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-advanced-analysis-gis#45]
NYC Parks ITT will be sharing these for us to add. There is apparently a public and a private endpoint we can work with. 

I'm hopeful we can use [the ArcGIS ImageServer Connector plugin](https://plugins.qgis.org/plugins/ImageServerConnector/) to make this possible. 

Currently waiting information from the client

**Comment by ebrelsford** [comment]
Sure or if there is a WMS or TMS endpoint we can use that's even easier--no plugin needed.

**Comment by ebrelsford** [comment]
Internal only:

Basemap: https://webmaps.parks.nycnet/public/rest/services/Basemaps/BasemapHillshade/MapServer

Simplified Basemap: https://webmaps.parks.nycnet/public/rest/services/Basemaps/BasemapSimple/MapServer

External:

Basemap: https://tiles.arcgis.com/tiles/xJHn8F2NTtwCMFtX/arcgis/rest/services/ParksBasemap/MapServer

Vector Basemap: https://tiles.arcgis.com/tiles/xJHn8F2NTtwCMFtX/arcgis/rest/services/VectorBasemap/VectorTileServer

**Comment by ebrelsford** [comment]
Using the External (Basemap) URL I can load some layers using the standard Data Source Manager:

![image](https://user-images.githubusercontent.com/375002/66967557-56bfbe00-f04f-11e9-8ecd-34cbbe561559.png)

I'm not sure how much this adds here?

**Comment by datapolitan** [comment]
We should use WMTS instead (https://tiles.arcgis.com/tiles/xJHn8F2NTtwCMFtX/arcgis/rest/services/ParksBasemap/MapServer/WMTS/1.0.0/WMTSCapabilities.xml?cacheKey=863bddb6622687b3)


![qgis-wmts-0](https://user-images.githubusercontent.com/7535465/67416635-2b7c2800-f595-11e9-9d88-ce79e0de6f4a.JPG)
![qgis-wmts-1](https://user-images.githubusercontent.com/7535465/67416636-2b7c2800-f595-11e9-9089-4a311f549630.JPG)
![qgis-wmts-2](https://user-images.githubusercontent.com/7535465/67416638-2b7c2800-f595-11e9-94ab-19489158d78e.JPG)
![qgis-wmts-3](https://user-images.githubusercontent.com/7535465/67416640-2b7c2800-f595-11e9-936e-141802f87edc.JPG)
