### ISSUE TITLE
Review the Problem Ideation/Process mapping section of the class

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-advanced-analysis-gis#47]
As per client request and our own interests of continuity, make sure we're emphasizing this process appropriately.

**Comment by ebrelsford** [comment]
From the feedback:

> In the generating ideas section there should be some general discussion of problem design in GIS, for example mapping out your workflow in advance, keeping track of the steps you took to transform the data, keeping your outputs and scratch files organized, and keeping the end product in mind (does the question I am trying to answer needs a map or could it be a table or graph?, if it is a map, will it be printed, should it be interactive?)
