### ISSUE TITLE
Add Export of CSV File

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-advanced-analysis-gis#48]
Demonstrate export of spatial data as CSV as part of our guided tutorials.

There are apparently [several ways to do this](https://gis.stackexchange.com/q/135801)
1. Right click `Save As...` -> Select CSV
2. Use the option in MMQGIS -> Import/Export -> Attributes Export to CSV File
3. Use the XY Tools Plugin

I'm inclined to option 1, though 2 is also appealing. I'd rather not introduce a new plug-in if we can help it, especially given our issues with QMS

**Comment by ebrelsford** [comment]
Option 1 is my preference, for sure.
