### ISSUE TITLE
Acknowledge Broken Link

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-advanced-analysis-gis#56]
The link http://www.geocontrolling.com/co-je-gis.htm redirects to a "domain is being updated." We should put an acknowledgement up to cover this so it's clear, but we don't have the time to find an appropriate replacement image.

Part of #40

**Comment by ebrelsford** [comment]
Could use

![](https://due-parsons.github.io/methods3-materials-fall2019/week1/img/layers.png)

originally via [Architect Magazine](https://www.architectmagazine.com/technology/gis-and-data-enriched-design_o)

**Comment by ebrelsford** [comment]
Replaced the original image with a different one, link is no longer broken.
